name: CI - Build and test solution

on:
  push:
jobs:
  build-and-test:
    name: CI - Build and Test
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Set up dot net
        uses: actions/setup-dotnet@v5
        with:
            global-json-file: global.json

      - name: Restore dependencies
        run: |
            dotnet restore ./src/DevOps.App/DevOps.App.slnx

      - name: Build solution
        run: |
            dotnet build ./src/DevOps.App/DevOps.App.slnx --no-restore --configuration Release

      - name: Run tests
        run: |
            dotnet test ./src/DevOps.App/DevOps.App.slnx --no-build --configuration Release